"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import TanStackProvider from "@/provider/TanStackProvider";
const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" w-full flex items-center justify-center h-fit py-10">
          <nav className=" p-5 rounded-lg border-gray-200 border-2 space-x-6">
            <Link
              href={"/"}
              className={`  ${path == "/product" ? "" : "underline"} `}
            >
              Home
            </Link>
            <Link
              className={`  ${path == "/product" ? "underline" : ""} `}
              href={"/product"}
            >
              Add Product
            </Link>
          </nav>
        </header>
        <TanStackProvider>{children}</TanStackProvider>
      </body>
    </html>
  );
}
